---
- name: System configuration and prerequisites
  hosts: all
  become: true

  roles:
    - partition
    - network
    - apt
    - timezone
    - movelogs
    - k3s/common

- name: K3s master
  hosts: master
  become: true

  roles:
    - k3s/master

- name: K3s nodes
  hosts: nodes
  become: true

  roles:
    - k3s/nodes
