---
# update
- name: Upgrade all apt packages
  tags: slow
  apt:
    upgrade: dist
    update_cache: yes

# Install useful stuff
- name: Install useful tools
  tags: slow
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - libraspberrypi-bin

- name: Check if a reboot is required
  register: reboot_required_file
  stat:
    path: /var/run/reboot-required
    get_md5: no

- name: Reboot for updates
  reboot:
    msg: "Reboot initiated by Ansible due to updates"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required_file.stat.exists
