---
- name: Read node token
  slurp:
    src: /ssd/k3s/server/node-token
  register: node_token

- name: Set node token fact
  set_fact:
    token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"
