---
- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Add cgroups settings to boot command line
  replace:
    path: /boot/firmware/cmdline.txt
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'
  with_items:
  - "cgroup_enable=cpuset"
  - "cgroup_enable=memory"
  - "cgroup_memory=1"
  register: cmdline

- name: Reboot for cgroups settings change
  reboot:
  when: cmdline.changed
