---
- name: Download k3s binary
  get_url:
    url: https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s-arm64
    checksum: sha256:https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/sha256sum-arm64.txt
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: "0755"

- name: Install k3s-killall.sh
  copy:
    src: ../files/k3s-killall.sh
    dest: /usr/local/bin/k3s-killall.sh
    mode: "0755"
