---
# Some USB SSD adapters don't support UAS, the new fast transfer mechanism. Revert back to USB mass storage for these to avoid errors.
# https://www.raspberrypi.org/forums/viewtopic.php?t=245931
# TODO: This should be conditionalized
- name: Add quirks to boot command line
  replace:
    path: /boot/firmware/cmdline.txt
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'
  with_items:
  - "usb-storage.quirks={{ quirks }}:u"
  register: cmdline

- name: Reboot for quirks change
  reboot:
  when: cmdline.changed
